@api=http://localhost:3000/api

### get books
GET {{api}}/books?userId=4


###
# insert book testing
POST {{api}}/books 

{
  "title": "Test Book12",
  "owner": 4,
  "clickdel": 0
}

### get a book
GET {{api}}/books/3

### update book
PATCH {{api}}/books/5

{
  "title": "TTT",
  "clickdel": 1
}

###

PUT {{api}}/books/6

{
  "title": "SSS",
  "clickdel": 1
}

### delete book
DELETE {{api}}/books/12

# =========================================

### get marks
GET {{api}}/marks


###
# insert mark testing
POST {{api}}/marks 

{
  "book": 1,
  "title": "Test Book12",
  "descript": "Test Book12",
  "url": "url",
  "image": "image",
}

### get a mark
GET {{api}}/marks/3

### update mark
PATCH {{api}}/marks/5

{
  "book": 1,
  "title": "121212121212121",
  "descript": "1212121212121",
  "url": "url",
  "image": "image",
}

###

PUT {{api}}/marks/6

{
  "book": 1,
  "title": "343434343434",
  "descript": "343434343434",
  "url": "url",
  "image": "image",
}

### delete mark
DELETE {{api}}/marks/12