import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next AppXXX',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex fixed fixed-top w-full justify-around bg-blue-300'>
          <Link href='/csr'>CSR</Link>
          <Link href='/ssg'>SSG</Link>
          <Link href='/ssr'>SSR</Link>
          <Link href='/isr'>ISR</Link>
          <Link href='/photos'>Photos</Link>
        </div>
        <div className='container flex min-h-screen flex-col items-center justify-between p-24'>
          {children}
        </div>
      </body>
    </html>
  );
}
