import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getTodo } from '@/lib/placeholder';

export const metadata: Metadata = {
  title: 'ToDo',
  description: 'Generated by create next app',
};

export default async function Todo({
  params: { todoId },
}: {
  params: { todoId: number };
}) {
  const todo = await getTodo(todoId);
  if (!todo.id) return notFound();

  return (
    <>
      <h1 className='text-2xl'>ID: {todo.id}</h1>
      <h3 className='text-xl'>{todo.title}</h3>
    </>
  );
}
